name: Deploy Bot

on:
  push:
    branches:
      - main

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  LANGUAGE: "DE"

jobs:
  run_bot:
    runs-on: windows 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run Bot
        run: dotnet run --configuration Release 
